// <auto-generated />
using CryptoDashWeb.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoDashWeb.Data.Migrations
{
    [DbContext(typeof(CryptoDashContext))]
    [Migration("20260917150454_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LayoutJson")
                        .HasColumnType("text")
                        .HasColumnName("layout_json");

                    b.Property<int>("TileId")
                        .HasColumnType("integer")
                        .HasColumnName("tile_id");

                    b.HasKey("Id")
                        .HasName("pk_layouts");

                    b.HasIndex("TileId")
                        .HasDatabaseName("ix_layouts_tile_id");

                    b.ToTable("layouts", "dbo");
                });

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.Tile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("ToolCode")
                        .HasColumnType("integer")
                        .HasColumnName("tool_code");

                    b.Property<int>("TypeCode")
                        .HasColumnType("integer")
                        .HasColumnName("type_code");

                    b.HasKey("Id")
                        .HasName("pk_tile_items");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_tile_items_parent_id");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("ix_tile_items_type_code");

                    b.ToTable("tile_items", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dashboard Layout",
                            ToolCode = 1,
                            TypeCode = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dashboard Filters",
                            ParentId = 1,
                            TypeCode = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dashboard Dashboard",
                            ParentId = 1,
                            TypeCode = 1
                        });
                });

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.TileType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tile_types");

                    b.ToTable("tile_types", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Form"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Filter"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Layout"
                        });
                });

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.Layout", b =>
                {
                    b.HasOne("CryptoDashWeb.Data.DBModels.Tile", "Tile")
                        .WithMany("Layouts")
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layouts_tile_items_tile_id");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.Tile", b =>
                {
                    b.HasOne("CryptoDashWeb.Data.DBModels.Tile", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tile_items_tile_items_parent_id");

                    b.HasOne("CryptoDashWeb.Data.DBModels.TileType", "TileType")
                        .WithMany("Tiles")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tile_items_tile_types_type_code");

                    b.Navigation("Parent");

                    b.Navigation("TileType");
                });

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.Tile", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Layouts");
                });

            modelBuilder.Entity("CryptoDashWeb.Data.DBModels.TileType", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
