// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Security.Data.DBContext;

#nullable disable

namespace Security.Data.Migrations
{
    [DbContext(typeof(SecurityContext))]
    partial class SecurityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sc")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("UsersRolesId")
                        .HasColumnType("integer")
                        .HasColumnName("users_roles_id");

                    b.Property<int>("UsersRolesId1")
                        .HasColumnType("integer")
                        .HasColumnName("users_roles_id1");

                    b.HasKey("UsersRolesId", "UsersRolesId1")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersRolesId1")
                        .HasDatabaseName("ix_role_user_users_roles_id1");

                    b.ToTable("role_user", "sc");
                });

            modelBuilder.Entity("Security.Data.DBModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", "sc");
                });

            modelBuilder.Entity("Security.Data.DBModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "sc");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Security.Data.DBModels.Role", null)
                        .WithMany()
                        .HasForeignKey("UsersRolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_roles_users_roles_id");

                    b.HasOne("Security.Data.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UsersRolesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_roles_id1");
                });

            modelBuilder.Entity("Security.Data.DBModels.User", b =>
                {
                    b.OwnsOne("Security.Data.Models.UserOptions", "OptionsJson", b1 =>
                        {
                            b1.Property<int>("UserId");

                            b1.Property<int>("Test");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "sc");

                            b1
                                .ToJson("options_json")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("OptionsJson");
                });
#pragma warning restore 612, 618
        }
    }
}
